version: 2.1

jobs:
  deploy:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Installing AWS CLI
          command: |
            sudo apt-get update
            sudo apt install python3-pip -y
            sudo pip3 install awsebcli --upgrade
      - run: npm install
      - run: aws s3 sync ./build s3://nft-website-cicd

workflows:
  deploy_directly:
    jobs:
      - deploy
